// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCustomMsg.proto

package ench;

public final class ServerCustomMsg {
  private ServerCustomMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 cmd = 1;
    boolean hasCmd();
    int getCmd();
    
    // repeated .CustomMsg.CustomParam params = 2;
    java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam> 
        getParamsList();
    ench.ServerCustomMsg.CustomMsg.CustomParam getParams(int index);
    int getParamsCount();
    java.util.List<? extends ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> 
        getParamsOrBuilderList();
    ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(
        int index);
  }
  public static final class CustomMsg extends
      com.google.protobuf.GeneratedMessage
      implements CustomMsgOrBuilder {
    // Use CustomMsg.newBuilder() to construct.
    private CustomMsg(Builder builder) {
      super(builder);
    }
    private CustomMsg(boolean noInit) {}
    
    private static final CustomMsg defaultInstance;
    public static CustomMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public CustomMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ench.ServerCustomMsg.internal_static_CustomMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ench.ServerCustomMsg.internal_static_CustomMsg_fieldAccessorTable;
    }
    
    public interface CustomParamOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string paramKey = 1;
      boolean hasParamKey();
      String getParamKey();
      
      // required .CustomMsg.ParamValue paramValues = 2;
      boolean hasParamValues();
      ench.ServerCustomMsg.CustomMsg.ParamValue getParamValues();
      ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder();
    }
    public static final class CustomParam extends
        com.google.protobuf.GeneratedMessage
        implements CustomParamOrBuilder {
      // Use CustomParam.newBuilder() to construct.
      private CustomParam(Builder builder) {
        super(builder);
      }
      private CustomParam(boolean noInit) {}
      
      private static final CustomParam defaultInstance;
      public static CustomParam getDefaultInstance() {
        return defaultInstance;
      }
      
      public CustomParam getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_CustomParam_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_CustomParam_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string paramKey = 1;
      public static final int PARAMKEY_FIELD_NUMBER = 1;
      private java.lang.Object paramKey_;
      public boolean hasParamKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getParamKey() {
        java.lang.Object ref = paramKey_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            paramKey_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getParamKeyBytes() {
        java.lang.Object ref = paramKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          paramKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required .CustomMsg.ParamValue paramValues = 2;
      public static final int PARAMVALUES_FIELD_NUMBER = 2;
      private ench.ServerCustomMsg.CustomMsg.ParamValue paramValues_;
      public boolean hasParamValues() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ench.ServerCustomMsg.CustomMsg.ParamValue getParamValues() {
        return paramValues_;
      }
      public ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder() {
        return paramValues_;
      }
      
      private void initFields() {
        paramKey_ = "";
        paramValues_ = ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasParamKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasParamValues()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getParamKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, paramValues_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getParamKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, paramValues_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ench.ServerCustomMsg.CustomMsg.CustomParam prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ench.ServerCustomMsg.internal_static_CustomMsg_CustomParam_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ench.ServerCustomMsg.internal_static_CustomMsg_CustomParam_fieldAccessorTable;
        }
        
        // Construct using ench.ServerCustomMsg.CustomMsg.CustomParam.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getParamValuesFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          paramKey_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (paramValuesBuilder_ == null) {
            paramValues_ = ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
          } else {
            paramValuesBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ench.ServerCustomMsg.CustomMsg.CustomParam.getDescriptor();
        }
        
        public ench.ServerCustomMsg.CustomMsg.CustomParam getDefaultInstanceForType() {
          return ench.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance();
        }
        
        public ench.ServerCustomMsg.CustomMsg.CustomParam build() {
          ench.ServerCustomMsg.CustomMsg.CustomParam result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ench.ServerCustomMsg.CustomMsg.CustomParam buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ench.ServerCustomMsg.CustomMsg.CustomParam result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ench.ServerCustomMsg.CustomMsg.CustomParam buildPartial() {
          ench.ServerCustomMsg.CustomMsg.CustomParam result = new ench.ServerCustomMsg.CustomMsg.CustomParam(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.paramKey_ = paramKey_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (paramValuesBuilder_ == null) {
            result.paramValues_ = paramValues_;
          } else {
            result.paramValues_ = paramValuesBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ench.ServerCustomMsg.CustomMsg.CustomParam) {
            return mergeFrom((ench.ServerCustomMsg.CustomMsg.CustomParam)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ench.ServerCustomMsg.CustomMsg.CustomParam other) {
          if (other == ench.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance()) return this;
          if (other.hasParamKey()) {
            setParamKey(other.getParamKey());
          }
          if (other.hasParamValues()) {
            mergeParamValues(other.getParamValues());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasParamKey()) {
            
            return false;
          }
          if (!hasParamValues()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                paramKey_ = input.readBytes();
                break;
              }
              case 18: {
                ench.ServerCustomMsg.CustomMsg.ParamValue.Builder subBuilder = ench.ServerCustomMsg.CustomMsg.ParamValue.newBuilder();
                if (hasParamValues()) {
                  subBuilder.mergeFrom(getParamValues());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setParamValues(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string paramKey = 1;
        private java.lang.Object paramKey_ = "";
        public boolean hasParamKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getParamKey() {
          java.lang.Object ref = paramKey_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            paramKey_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setParamKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          paramKey_ = value;
          onChanged();
          return this;
        }
        public Builder clearParamKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          paramKey_ = getDefaultInstance().getParamKey();
          onChanged();
          return this;
        }
        void setParamKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          paramKey_ = value;
          onChanged();
        }
        
        // required .CustomMsg.ParamValue paramValues = 2;
        private ench.ServerCustomMsg.CustomMsg.ParamValue paramValues_ = ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            ench.ServerCustomMsg.CustomMsg.ParamValue, ench.ServerCustomMsg.CustomMsg.ParamValue.Builder, ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder> paramValuesBuilder_;
        public boolean hasParamValues() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public ench.ServerCustomMsg.CustomMsg.ParamValue getParamValues() {
          if (paramValuesBuilder_ == null) {
            return paramValues_;
          } else {
            return paramValuesBuilder_.getMessage();
          }
        }
        public Builder setParamValues(ench.ServerCustomMsg.CustomMsg.ParamValue value) {
          if (paramValuesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            paramValues_ = value;
            onChanged();
          } else {
            paramValuesBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder setParamValues(
            ench.ServerCustomMsg.CustomMsg.ParamValue.Builder builderForValue) {
          if (paramValuesBuilder_ == null) {
            paramValues_ = builderForValue.build();
            onChanged();
          } else {
            paramValuesBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder mergeParamValues(ench.ServerCustomMsg.CustomMsg.ParamValue value) {
          if (paramValuesBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                paramValues_ != ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance()) {
              paramValues_ =
                ench.ServerCustomMsg.CustomMsg.ParamValue.newBuilder(paramValues_).mergeFrom(value).buildPartial();
            } else {
              paramValues_ = value;
            }
            onChanged();
          } else {
            paramValuesBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder clearParamValues() {
          if (paramValuesBuilder_ == null) {
            paramValues_ = ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
            onChanged();
          } else {
            paramValuesBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        public ench.ServerCustomMsg.CustomMsg.ParamValue.Builder getParamValuesBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getParamValuesFieldBuilder().getBuilder();
        }
        public ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder() {
          if (paramValuesBuilder_ != null) {
            return paramValuesBuilder_.getMessageOrBuilder();
          } else {
            return paramValues_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            ench.ServerCustomMsg.CustomMsg.ParamValue, ench.ServerCustomMsg.CustomMsg.ParamValue.Builder, ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder> 
            getParamValuesFieldBuilder() {
          if (paramValuesBuilder_ == null) {
            paramValuesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                ench.ServerCustomMsg.CustomMsg.ParamValue, ench.ServerCustomMsg.CustomMsg.ParamValue.Builder, ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder>(
                    paramValues_,
                    getParentForChildren(),
                    isClean());
            paramValues_ = null;
          }
          return paramValuesBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:CustomMsg.CustomParam)
      }
      
      static {
        defaultInstance = new CustomParam(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:CustomMsg.CustomParam)
    }
    
    public interface ParamValueOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated string value = 1;
      java.util.List<String> getValueList();
      int getValueCount();
      String getValue(int index);
    }
    public static final class ParamValue extends
        com.google.protobuf.GeneratedMessage
        implements ParamValueOrBuilder {
      // Use ParamValue.newBuilder() to construct.
      private ParamValue(Builder builder) {
        super(builder);
      }
      private ParamValue(boolean noInit) {}
      
      private static final ParamValue defaultInstance;
      public static ParamValue getDefaultInstance() {
        return defaultInstance;
      }
      
      public ParamValue getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_ParamValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_ParamValue_fieldAccessorTable;
      }
      
      // repeated string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList value_;
      public java.util.List<String>
          getValueList() {
        return value_;
      }
      public int getValueCount() {
        return value_.size();
      }
      public String getValue(int index) {
        return value_.get(index);
      }
      
      private void initFields() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < value_.size(); i++) {
          output.writeBytes(1, value_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(value_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ench.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ench.ServerCustomMsg.CustomMsg.ParamValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ench.ServerCustomMsg.CustomMsg.ParamValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ench.ServerCustomMsg.internal_static_CustomMsg_ParamValue_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ench.ServerCustomMsg.internal_static_CustomMsg_ParamValue_fieldAccessorTable;
        }
        
        // Construct using ench.ServerCustomMsg.CustomMsg.ParamValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ench.ServerCustomMsg.CustomMsg.ParamValue.getDescriptor();
        }
        
        public ench.ServerCustomMsg.CustomMsg.ParamValue getDefaultInstanceForType() {
          return ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
        }
        
        public ench.ServerCustomMsg.CustomMsg.ParamValue build() {
          ench.ServerCustomMsg.CustomMsg.ParamValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ench.ServerCustomMsg.CustomMsg.ParamValue buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ench.ServerCustomMsg.CustomMsg.ParamValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ench.ServerCustomMsg.CustomMsg.ParamValue buildPartial() {
          ench.ServerCustomMsg.CustomMsg.ParamValue result = new ench.ServerCustomMsg.CustomMsg.ParamValue(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.UnmodifiableLazyStringList(
                value_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ench.ServerCustomMsg.CustomMsg.ParamValue) {
            return mergeFrom((ench.ServerCustomMsg.CustomMsg.ParamValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ench.ServerCustomMsg.CustomMsg.ParamValue other) {
          if (other == ench.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance()) return this;
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                ensureValueIsMutable();
                value_.add(input.readBytes());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated string value = 1;
        private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.LazyStringArrayList(value_);
            bitField0_ |= 0x00000001;
           }
        }
        public java.util.List<String>
            getValueList() {
          return java.util.Collections.unmodifiableList(value_);
        }
        public int getValueCount() {
          return value_.size();
        }
        public String getValue(int index) {
          return value_.get(index);
        }
        public Builder setValue(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllValue(
            java.lang.Iterable<String> values) {
          ensureValueIsMutable();
          super.addAll(values, value_);
          onChanged();
          return this;
        }
        public Builder clearValue() {
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        void addValue(com.google.protobuf.ByteString value) {
          ensureValueIsMutable();
          value_.add(value);
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:CustomMsg.ParamValue)
      }
      
      static {
        defaultInstance = new ParamValue(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:CustomMsg.ParamValue)
    }
    
    private int bitField0_;
    // required int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCmd() {
      return cmd_;
    }
    
    // repeated .CustomMsg.CustomParam params = 2;
    public static final int PARAMS_FIELD_NUMBER = 2;
    private java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam> params_;
    public java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam> getParamsList() {
      return params_;
    }
    public java.util.List<? extends ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    public int getParamsCount() {
      return params_.size();
    }
    public ench.ServerCustomMsg.CustomMsg.CustomParam getParams(int index) {
      return params_.get(index);
    }
    public ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }
    
    private void initFields() {
      cmd_ = 0;
      params_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParamsCount(); i++) {
        if (!getParams(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(2, params_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, params_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ench.ServerCustomMsg.CustomMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ench.ServerCustomMsg.CustomMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ench.ServerCustomMsg.CustomMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ench.ServerCustomMsg.CustomMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ench.ServerCustomMsg.internal_static_CustomMsg_fieldAccessorTable;
      }
      
      // Construct using ench.ServerCustomMsg.CustomMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParamsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ench.ServerCustomMsg.CustomMsg.getDescriptor();
      }
      
      public ench.ServerCustomMsg.CustomMsg getDefaultInstanceForType() {
        return ench.ServerCustomMsg.CustomMsg.getDefaultInstance();
      }
      
      public ench.ServerCustomMsg.CustomMsg build() {
        ench.ServerCustomMsg.CustomMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ench.ServerCustomMsg.CustomMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ench.ServerCustomMsg.CustomMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ench.ServerCustomMsg.CustomMsg buildPartial() {
        ench.ServerCustomMsg.CustomMsg result = new ench.ServerCustomMsg.CustomMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ench.ServerCustomMsg.CustomMsg) {
          return mergeFrom((ench.ServerCustomMsg.CustomMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ench.ServerCustomMsg.CustomMsg other) {
        if (other == ench.ServerCustomMsg.CustomMsg.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        for (int i = 0; i < getParamsCount(); i++) {
          if (!getParams(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              ench.ServerCustomMsg.CustomMsg.CustomParam.Builder subBuilder = ench.ServerCustomMsg.CustomMsg.CustomParam.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addParams(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 cmd = 1;
      private int cmd_ ;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCmd() {
        return cmd_;
      }
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .CustomMsg.CustomParam params = 2;
      private java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = new java.util.ArrayList<ench.ServerCustomMsg.CustomMsg.CustomParam>(params_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ench.ServerCustomMsg.CustomMsg.CustomParam, ench.ServerCustomMsg.CustomMsg.CustomParam.Builder, ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> paramsBuilder_;
      
      public java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      public ench.ServerCustomMsg.CustomMsg.CustomParam getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      public Builder setParams(
          int index, ench.ServerCustomMsg.CustomMsg.CustomParam value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setParams(
          int index, ench.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addParams(ench.ServerCustomMsg.CustomMsg.CustomParam value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addParams(
          int index, ench.ServerCustomMsg.CustomMsg.CustomParam value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addParams(
          ench.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addParams(
          int index, ench.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllParams(
          java.lang.Iterable<? extends ench.ServerCustomMsg.CustomMsg.CustomParam> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          super.addAll(values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      public ench.ServerCustomMsg.CustomMsg.CustomParam.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      public ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      public ench.ServerCustomMsg.CustomMsg.CustomParam.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            ench.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance());
      }
      public ench.ServerCustomMsg.CustomMsg.CustomParam.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, ench.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance());
      }
      public java.util.List<ench.ServerCustomMsg.CustomMsg.CustomParam.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ench.ServerCustomMsg.CustomMsg.CustomParam, ench.ServerCustomMsg.CustomMsg.CustomParam.Builder, ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ench.ServerCustomMsg.CustomMsg.CustomParam, ench.ServerCustomMsg.CustomMsg.CustomParam.Builder, ench.ServerCustomMsg.CustomMsg.CustomParamOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:CustomMsg)
    }
    
    static {
      defaultInstance = new CustomMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CustomMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMsg_CustomParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomMsg_CustomParam_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMsg_ParamValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomMsg_ParamValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ServerCustomMsg.proto\"\252\001\n\tCustomMsg\022\013\n" +
      "\003cmd\030\001 \002(\005\022&\n\006params\030\002 \003(\0132\026.CustomMsg.C" +
      "ustomParam\032K\n\013CustomParam\022\020\n\010paramKey\030\001 " +
      "\002(\t\022*\n\013paramValues\030\002 \002(\0132\025.CustomMsg.Par" +
      "amValue\032\033\n\nParamValue\022\r\n\005value\030\001 \003(\tB\027\n\004" +
      "enchB\017ServerCustomMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CustomMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CustomMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomMsg_descriptor,
              new java.lang.String[] { "Cmd", "Params", },
              ench.ServerCustomMsg.CustomMsg.class,
              ench.ServerCustomMsg.CustomMsg.Builder.class);
          internal_static_CustomMsg_CustomParam_descriptor =
            internal_static_CustomMsg_descriptor.getNestedTypes().get(0);
          internal_static_CustomMsg_CustomParam_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomMsg_CustomParam_descriptor,
              new java.lang.String[] { "ParamKey", "ParamValues", },
              ench.ServerCustomMsg.CustomMsg.CustomParam.class,
              ench.ServerCustomMsg.CustomMsg.CustomParam.Builder.class);
          internal_static_CustomMsg_ParamValue_descriptor =
            internal_static_CustomMsg_descriptor.getNestedTypes().get(1);
          internal_static_CustomMsg_ParamValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomMsg_ParamValue_descriptor,
              new java.lang.String[] { "Value", },
              ench.ServerCustomMsg.CustomMsg.ParamValue.class,
              ench.ServerCustomMsg.CustomMsg.ParamValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
