// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCustomMsg.proto

package com.netty.game.server.msg;

import java.util.List;

public final class ServerCustomMsg {
	private ServerCustomMsg() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CustomMsgOrBuilder extends
			// @@protoc_insertion_point(interface_extends:CustomMsg)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required int32 cmd = 1;</code>
		 */
		boolean hasCmd();

		/**
		 * <code>required int32 cmd = 1;</code>
		 */
		int getCmd();

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> getParamsList();

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam getParams(int index);

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		int getParamsCount();

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		java.util.List<? extends com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> getParamsOrBuilderList();

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code CustomMsg}
	 */
	public static final class CustomMsg extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:CustomMsg)
			CustomMsgOrBuilder {
		// Use CustomMsg.newBuilder() to construct.
		private CustomMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CustomMsg(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final CustomMsg defaultInstance;

		public static CustomMsg getDefaultInstance() {
			return defaultInstance;
		}

		public CustomMsg getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CustomMsg(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						cmd_ = input.readInt32();
						break;
					}
					case 18: {
						if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
							params_ = new java.util.ArrayList<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam>();
							mutable_bitField0_ |= 0x00000002;
						}
						params_.add(input.readMessage(
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.PARSER,
								extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
					params_ = java.util.Collections.unmodifiableList(params_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.class,
							com.netty.game.server.msg.ServerCustomMsg.CustomMsg.Builder.class);
		}

		public static com.google.protobuf.Parser<CustomMsg> PARSER = new com.google.protobuf.AbstractParser<CustomMsg>() {
			public CustomMsg parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return new CustomMsg(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CustomMsg> getParserForType() {
			return PARSER;
		}

		public interface CustomParamOrBuilder extends
				// @@protoc_insertion_point(interface_extends:CustomMsg.CustomParam)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			boolean hasParamKey();

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			java.lang.String getParamKey();

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			com.google.protobuf.ByteString getParamKeyBytes();

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			boolean hasParamValues();

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue getParamValues();

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder();
		}

		/**
		 * Protobuf type {@code CustomMsg.CustomParam}
		 */
		public static final class CustomParam extends com.google.protobuf.GeneratedMessage implements
				// @@protoc_insertion_point(message_implements:CustomMsg.CustomParam)
				CustomParamOrBuilder {
			// Use CustomParam.newBuilder() to construct.
			private CustomParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private CustomParam(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final CustomParam defaultInstance;

			public static CustomParam getDefaultInstance() {
				return defaultInstance;
			}

			public CustomParam getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private CustomParam(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000001;
							paramKey_ = bs;
							break;
						}
						case 18: {
							com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder subBuilder = null;
							if (((bitField0_ & 0x00000002) == 0x00000002)) {
								subBuilder = paramValues_.toBuilder();
							}
							paramValues_ = input.readMessage(
									com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.PARSER,
									extensionRegistry);
							if (subBuilder != null) {
								subBuilder.mergeFrom(paramValues_);
								paramValues_ = subBuilder.buildPartial();
							}
							bitField0_ |= 0x00000002;
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
							.setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_CustomParam_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_CustomParam_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.class,
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder.class);
			}

			public static com.google.protobuf.Parser<CustomParam> PARSER = new com.google.protobuf.AbstractParser<CustomParam>() {
				public CustomParam parsePartialFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
								throws com.google.protobuf.InvalidProtocolBufferException {
					return new CustomParam(input, extensionRegistry);
				}
			};

			@java.lang.Override
			public com.google.protobuf.Parser<CustomParam> getParserForType() {
				return PARSER;
			}

			private int bitField0_;
			public static final int PARAMKEY_FIELD_NUMBER = 1;
			private java.lang.Object paramKey_;

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			public boolean hasParamKey() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			public java.lang.String getParamKey() {
				java.lang.Object ref = paramKey_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						paramKey_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>required string paramKey = 1;</code>
			 */
			public com.google.protobuf.ByteString getParamKeyBytes() {
				java.lang.Object ref = paramKey_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					paramKey_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int PARAMVALUES_FIELD_NUMBER = 2;
			private com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue paramValues_;

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			public boolean hasParamValues() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue getParamValues() {
				return paramValues_;
			}

			/**
			 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder() {
				return paramValues_;
			}

			private void initFields() {
				paramKey_ = "";
				paramValues_ = com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
			}

			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1)
					return true;
				if (isInitialized == 0)
					return false;

				if (!hasParamKey()) {
					memoizedIsInitialized = 0;
					return false;
				}
				if (!hasParamValues()) {
					memoizedIsInitialized = 0;
					return false;
				}
				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					output.writeBytes(1, getParamKeyBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					output.writeMessage(2, paramValues_);
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getParamKeyBytes());
				}
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, paramValues_);
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseDelimitedFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseDelimitedFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code CustomMsg.CustomParam}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>implements
					// @@protoc_insertion_point(builder_implements:CustomMsg.CustomParam)
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_CustomParam_descriptor;
				}

				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_CustomParam_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.class,
									com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder.class);
				}

				// Construct using
				// com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
						getParamValuesFieldBuilder();
					}
				}

				private static Builder create() {
					return new Builder();
				}

				public Builder clear() {
					super.clear();
					paramKey_ = "";
					bitField0_ = (bitField0_ & ~0x00000001);
					if (paramValuesBuilder_ == null) {
						paramValues_ = com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue
								.getDefaultInstance();
					} else {
						paramValuesBuilder_.clear();
					}
					bitField0_ = (bitField0_ & ~0x00000002);
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_CustomParam_descriptor;
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam getDefaultInstanceForType() {
					return com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance();
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam build() {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam buildPartial() {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam result = new com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam(
							this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
						to_bitField0_ |= 0x00000001;
					}
					result.paramKey_ = paramKey_;
					if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
						to_bitField0_ |= 0x00000002;
					}
					if (paramValuesBuilder_ == null) {
						result.paramValues_ = paramValues_;
					} else {
						result.paramValues_ = paramValuesBuilder_.build();
					}
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam) {
						return mergeFrom((com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam other) {
					if (other == com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance())
						return this;
					if (other.hasParamKey()) {
						bitField0_ |= 0x00000001;
						paramKey_ = other.paramKey_;
						onChanged();
					}
					if (other.hasParamValues()) {
						mergeParamValues(other.getParamValues());
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				public final boolean isInitialized() {
					if (!hasParamKey()) {

						return false;
					}
					if (!hasParamValues()) {

						return false;
					}
					return true;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam) e
								.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private int bitField0_;

				private java.lang.Object paramKey_ = "";

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public boolean hasParamKey() {
					return ((bitField0_ & 0x00000001) == 0x00000001);
				}

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public java.lang.String getParamKey() {
					java.lang.Object ref = paramKey_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						if (bs.isValidUtf8()) {
							paramKey_ = s;
						}
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public com.google.protobuf.ByteString getParamKeyBytes() {
					java.lang.Object ref = paramKey_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString
								.copyFromUtf8((java.lang.String) ref);
						paramKey_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public Builder setParamKey(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					paramKey_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public Builder clearParamKey() {
					bitField0_ = (bitField0_ & ~0x00000001);
					paramKey_ = getDefaultInstance().getParamKey();
					onChanged();
					return this;
				}

				/**
				 * <code>required string paramKey = 1;</code>
				 */
				public Builder setParamKeyBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					paramKey_ = value;
					onChanged();
					return this;
				}

				private com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue paramValues_ = com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue
						.getDefaultInstance();
				private com.google.protobuf.SingleFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder> paramValuesBuilder_;

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public boolean hasParamValues() {
					return ((bitField0_ & 0x00000002) == 0x00000002);
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue getParamValues() {
					if (paramValuesBuilder_ == null) {
						return paramValues_;
					} else {
						return paramValuesBuilder_.getMessage();
					}
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public Builder setParamValues(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue value) {
					if (paramValuesBuilder_ == null) {
						if (value == null) {
							throw new NullPointerException();
						}
						paramValues_ = value;
						onChanged();
					} else {
						paramValuesBuilder_.setMessage(value);
					}
					bitField0_ |= 0x00000002;
					return this;
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public Builder setParamValues(
						com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder builderForValue) {
					if (paramValuesBuilder_ == null) {
						paramValues_ = builderForValue.build();
						onChanged();
					} else {
						paramValuesBuilder_.setMessage(builderForValue.build());
					}
					bitField0_ |= 0x00000002;
					return this;
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public Builder mergeParamValues(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue value) {
					if (paramValuesBuilder_ == null) {
						if (((bitField0_ & 0x00000002) == 0x00000002)
								&& paramValues_ != com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue
										.getDefaultInstance()) {
							paramValues_ = com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue
									.newBuilder(paramValues_).mergeFrom(value).buildPartial();
						} else {
							paramValues_ = value;
						}
						onChanged();
					} else {
						paramValuesBuilder_.mergeFrom(value);
					}
					bitField0_ |= 0x00000002;
					return this;
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public Builder clearParamValues() {
					if (paramValuesBuilder_ == null) {
						paramValues_ = com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue
								.getDefaultInstance();
						onChanged();
					} else {
						paramValuesBuilder_.clear();
					}
					bitField0_ = (bitField0_ & ~0x00000002);
					return this;
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder getParamValuesBuilder() {
					bitField0_ |= 0x00000002;
					onChanged();
					return getParamValuesFieldBuilder().getBuilder();
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder getParamValuesOrBuilder() {
					if (paramValuesBuilder_ != null) {
						return paramValuesBuilder_.getMessageOrBuilder();
					} else {
						return paramValues_;
					}
				}

				/**
				 * <code>required .CustomMsg.ParamValue paramValues = 2;</code>
				 */
				private com.google.protobuf.SingleFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder> getParamValuesFieldBuilder() {
					if (paramValuesBuilder_ == null) {
						paramValuesBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder>(
								getParamValues(), getParentForChildren(), isClean());
						paramValues_ = null;
					}
					return paramValuesBuilder_;
				}

				// @@protoc_insertion_point(builder_scope:CustomMsg.CustomParam)
			}

			static {
				defaultInstance = new CustomParam(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:CustomMsg.CustomParam)
		}

		public interface ParamValueOrBuilder extends
				// @@protoc_insertion_point(interface_extends:CustomMsg.ParamValue)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>repeated string value = 1;</code>
			 */
			com.google.protobuf.ProtocolStringList getValueList();

			/**
			 * <code>repeated string value = 1;</code>
			 */
			int getValueCount();

			/**
			 * <code>repeated string value = 1;</code>
			 */
			java.lang.String getValue(int index);

			/**
			 * <code>repeated string value = 1;</code>
			 */
			com.google.protobuf.ByteString getValueBytes(int index);
		}

		/**
		 * Protobuf type {@code CustomMsg.ParamValue}
		 */
		public static final class ParamValue extends com.google.protobuf.GeneratedMessage implements
				// @@protoc_insertion_point(message_implements:CustomMsg.ParamValue)
				ParamValueOrBuilder {
			// Use ParamValue.newBuilder() to construct.
			private ParamValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private ParamValue(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final ParamValue defaultInstance;

			public static ParamValue getDefaultInstance() {
				return defaultInstance;
			}

			public ParamValue getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private ParamValue(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				int mutable_bitField0_ = 0;
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							com.google.protobuf.ByteString bs = input.readBytes();
							if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
								value_ = new com.google.protobuf.LazyStringArrayList();
								mutable_bitField0_ |= 0x00000001;
							}
							value_.add(bs);
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
							.setUnfinishedMessage(this);
				} finally {
					if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
						value_ = value_.getUnmodifiableView();
					}
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_ParamValue_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_ParamValue_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.class,
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder.class);
			}

			public static com.google.protobuf.Parser<ParamValue> PARSER = new com.google.protobuf.AbstractParser<ParamValue>() {
				public ParamValue parsePartialFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
								throws com.google.protobuf.InvalidProtocolBufferException {
					return new ParamValue(input, extensionRegistry);
				}
			};

			@java.lang.Override
			public com.google.protobuf.Parser<ParamValue> getParserForType() {
				return PARSER;
			}

			public static final int VALUE_FIELD_NUMBER = 1;
			private com.google.protobuf.LazyStringList value_;

			/**
			 * <code>repeated string value = 1;</code>
			 */
			public com.google.protobuf.ProtocolStringList getValueList() {
				return value_;
			}

			/**
			 * <code>repeated string value = 1;</code>
			 */
			public int getValueCount() {
				return value_.size();
			}

			/**
			 * <code>repeated string value = 1;</code>
			 */
			public java.lang.String getValue(int index) {
				return value_.get(index);
			}

			/**
			 * <code>repeated string value = 1;</code>
			 */
			public com.google.protobuf.ByteString getValueBytes(int index) {
				return value_.getByteString(index);
			}

			private void initFields() {
				value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			}

			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1)
					return true;
				if (isInitialized == 0)
					return false;

				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				for (int i = 0; i < value_.size(); i++) {
					output.writeBytes(1, value_.getByteString(i));
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				{
					int dataSize = 0;
					for (int i = 0; i < value_.size(); i++) {
						dataSize += com.google.protobuf.CodedOutputStream
								.computeBytesSizeNoTag(value_.getByteString(i));
					}
					size += dataSize;
					size += 1 * getValueList().size();
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseDelimitedFrom(
					java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseDelimitedFrom(
					java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parseFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code CustomMsg.ParamValue}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>implements
					// @@protoc_insertion_point(builder_implements:CustomMsg.ParamValue)
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValueOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_ParamValue_descriptor;
				}

				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_ParamValue_fieldAccessorTable
							.ensureFieldAccessorsInitialized(
									com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.class,
									com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.Builder.class);
				}

				// Construct using
				// com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					}
				}

				private static Builder create() {
					return new Builder();
				}

				public Builder clear() {
					super.clear();
					value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
					bitField0_ = (bitField0_ & ~0x00000001);
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_ParamValue_descriptor;
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue getDefaultInstanceForType() {
					return com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance();
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue build() {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue buildPartial() {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue result = new com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue(
							this);
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						value_ = value_.getUnmodifiableView();
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.value_ = value_;
					onBuilt();
					return result;
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue) {
						return mergeFrom((com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue other) {
					if (other == com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue.getDefaultInstance())
						return this;
					if (!other.value_.isEmpty()) {
						if (value_.isEmpty()) {
							value_ = other.value_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureValueIsMutable();
							value_.addAll(other.value_);
						}
						onChanged();
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				public final boolean isInitialized() {
					return true;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (com.netty.game.server.msg.ServerCustomMsg.CustomMsg.ParamValue) e
								.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private int bitField0_;

				private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;

				private void ensureValueIsMutable() {
					if (!((bitField0_ & 0x00000001) == 0x00000001)) {
						value_ = new com.google.protobuf.LazyStringArrayList(value_);
						bitField0_ |= 0x00000001;
					}
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public com.google.protobuf.ProtocolStringList getValueList() {
					return value_.getUnmodifiableView();
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public int getValueCount() {
					return value_.size();
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public java.lang.String getValue(int index) {
					return value_.get(index);
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public com.google.protobuf.ByteString getValueBytes(int index) {
					return value_.getByteString(index);
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public Builder setValue(int index, java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValueIsMutable();
					value_.set(index, value);
					onChanged();
					return this;
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public Builder addValue(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValueIsMutable();
					value_.add(value);
					onChanged();
					return this;
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public Builder addAllValue(java.lang.Iterable<java.lang.String> values) {
					ensureValueIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, value_);
					onChanged();
					return this;
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public Builder clearValue() {
					value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
					return this;
				}

				/**
				 * <code>repeated string value = 1;</code>
				 */
				public Builder addValueBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureValueIsMutable();
					value_.add(value);
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:CustomMsg.ParamValue)
			}

			static {
				defaultInstance = new ParamValue(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:CustomMsg.ParamValue)
		}

		private int bitField0_;
		public static final int CMD_FIELD_NUMBER = 1;
		private int cmd_;

		/**
		 * <code>required int32 cmd = 1;</code>
		 */
		public boolean hasCmd() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 cmd = 1;</code>
		 */
		public int getCmd() {
			return cmd_;
		}

		public static final int PARAMS_FIELD_NUMBER = 2;
		private java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> params_;

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		public java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> getParamsList() {
			return params_;
		}

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		public java.util.List<? extends com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> getParamsOrBuilderList() {
			return params_;
		}

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		public int getParamsCount() {
			return params_.size();
		}

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam getParams(int index) {
			return params_.get(index);
		}

		/**
		 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
		 */
		public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(int index) {
			return params_.get(index);
		}

		public java.lang.String getParamValueByKey(String key) {
			if (params_ == null || params_.isEmpty()) {
				return null;
			}
			for (CustomParam customParam : params_) {
				if (customParam.getParamKey().equalsIgnoreCase(key)) {
					ParamValue paramValues = customParam.getParamValues();
					if (paramValues == null) {
						return null;
					}
					List<String> values = paramValues.getValueList();
					if (values == null || values.isEmpty()) {
						return null;
					}
					return values.get(0);
				}
			}
			return null;
		}

		private void initFields() {
			cmd_ = 0;
			params_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasCmd()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getParamsCount(); i++) {
				if (!getParams(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, cmd_);
			}
			for (int i = 0; i < params_.size(); i++) {
				output.writeMessage(2, params_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, cmd_);
			}
			for (int i = 0; i < params_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, params_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.netty.game.server.msg.ServerCustomMsg.CustomMsg parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.netty.game.server.msg.ServerCustomMsg.CustomMsg prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CustomMsg}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>implements
				// @@protoc_insertion_point(builder_implements:CustomMsg)
				com.netty.game.server.msg.ServerCustomMsg.CustomMsgOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.class,
								com.netty.game.server.msg.ServerCustomMsg.CustomMsg.Builder.class);
			}

			// Construct using
			// com.netty.game.server.msg.ServerCustomMsg.CustomMsg.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getParamsFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				cmd_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				if (paramsBuilder_ == null) {
					params_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					paramsBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.netty.game.server.msg.ServerCustomMsg.internal_static_CustomMsg_descriptor;
			}

			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg getDefaultInstanceForType() {
				return com.netty.game.server.msg.ServerCustomMsg.CustomMsg.getDefaultInstance();
			}

			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg build() {
				com.netty.game.server.msg.ServerCustomMsg.CustomMsg result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg buildPartial() {
				com.netty.game.server.msg.ServerCustomMsg.CustomMsg result = new com.netty.game.server.msg.ServerCustomMsg.CustomMsg(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.cmd_ = cmd_;
				if (paramsBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						params_ = java.util.Collections.unmodifiableList(params_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.params_ = params_;
				} else {
					result.params_ = paramsBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.netty.game.server.msg.ServerCustomMsg.CustomMsg) {
					return mergeFrom((com.netty.game.server.msg.ServerCustomMsg.CustomMsg) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.netty.game.server.msg.ServerCustomMsg.CustomMsg other) {
				if (other == com.netty.game.server.msg.ServerCustomMsg.CustomMsg.getDefaultInstance())
					return this;
				if (other.hasCmd()) {
					setCmd(other.getCmd());
				}
				if (paramsBuilder_ == null) {
					if (!other.params_.isEmpty()) {
						if (params_.isEmpty()) {
							params_ = other.params_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureParamsIsMutable();
							params_.addAll(other.params_);
						}
						onChanged();
					}
				} else {
					if (!other.params_.isEmpty()) {
						if (paramsBuilder_.isEmpty()) {
							paramsBuilder_.dispose();
							paramsBuilder_ = null;
							params_ = other.params_;
							bitField0_ = (bitField0_ & ~0x00000002);
							paramsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
									? getParamsFieldBuilder() : null;
						} else {
							paramsBuilder_.addAllMessages(other.params_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasCmd()) {

					return false;
				}
				for (int i = 0; i < getParamsCount(); i++) {
					if (!getParams(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.netty.game.server.msg.ServerCustomMsg.CustomMsg parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.netty.game.server.msg.ServerCustomMsg.CustomMsg) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int cmd_;

			/**
			 * <code>required int32 cmd = 1;</code>
			 */
			public boolean hasCmd() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 cmd = 1;</code>
			 */
			public int getCmd() {
				return cmd_;
			}

			/**
			 * <code>required int32 cmd = 1;</code>
			 */
			public Builder setCmd(int value) {
				bitField0_ |= 0x00000001;
				cmd_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 cmd = 1;</code>
			 */
			public Builder clearCmd() {
				bitField0_ = (bitField0_ & ~0x00000001);
				cmd_ = 0;
				onChanged();
				return this;
			}

			private java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> params_ = java.util.Collections
					.emptyList();

			private void ensureParamsIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					params_ = new java.util.ArrayList<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam>(
							params_);
					bitField0_ |= 0x00000002;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> paramsBuilder_;

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> getParamsList() {
				if (paramsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(params_);
				} else {
					return paramsBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public int getParamsCount() {
				if (paramsBuilder_ == null) {
					return params_.size();
				} else {
					return paramsBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam getParams(int index) {
				if (paramsBuilder_ == null) {
					return params_.get(index);
				} else {
					return paramsBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder setParams(int index, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam value) {
				if (paramsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamsIsMutable();
					params_.set(index, value);
					onChanged();
				} else {
					paramsBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder setParams(int index,
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
				if (paramsBuilder_ == null) {
					ensureParamsIsMutable();
					params_.set(index, builderForValue.build());
					onChanged();
				} else {
					paramsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder addParams(com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam value) {
				if (paramsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamsIsMutable();
					params_.add(value);
					onChanged();
				} else {
					paramsBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder addParams(int index, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam value) {
				if (paramsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParamsIsMutable();
					params_.add(index, value);
					onChanged();
				} else {
					paramsBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder addParams(
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
				if (paramsBuilder_ == null) {
					ensureParamsIsMutable();
					params_.add(builderForValue.build());
					onChanged();
				} else {
					paramsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder addParams(int index,
					com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder builderForValue) {
				if (paramsBuilder_ == null) {
					ensureParamsIsMutable();
					params_.add(index, builderForValue.build());
					onChanged();
				} else {
					paramsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder addAllParams(
					java.lang.Iterable<? extends com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam> values) {
				if (paramsBuilder_ == null) {
					ensureParamsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, params_);
					onChanged();
				} else {
					paramsBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder clearParams() {
				if (paramsBuilder_ == null) {
					params_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					paramsBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public Builder removeParams(int index) {
				if (paramsBuilder_ == null) {
					ensureParamsIsMutable();
					params_.remove(index);
					onChanged();
				} else {
					paramsBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder getParamsBuilder(int index) {
				return getParamsFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder getParamsOrBuilder(
					int index) {
				if (paramsBuilder_ == null) {
					return params_.get(index);
				} else {
					return paramsBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public java.util.List<? extends com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> getParamsOrBuilderList() {
				if (paramsBuilder_ != null) {
					return paramsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(params_);
				}
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder addParamsBuilder() {
				return getParamsFieldBuilder().addBuilder(
						com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance());
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder addParamsBuilder(int index) {
				return getParamsFieldBuilder().addBuilder(index,
						com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.getDefaultInstance());
			}

			/**
			 * <code>repeated .CustomMsg.CustomParam params = 2;</code>
			 */
			public java.util.List<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder> getParamsBuilderList() {
				return getParamsFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder> getParamsFieldBuilder() {
				if (paramsBuilder_ == null) {
					paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParam.Builder, com.netty.game.server.msg.ServerCustomMsg.CustomMsg.CustomParamOrBuilder>(
							params_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
					params_ = null;
				}
				return paramsBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:CustomMsg)
		}

		static {
			defaultInstance = new CustomMsg(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:CustomMsg)
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_CustomMsg_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CustomMsg_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_CustomMsg_CustomParam_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CustomMsg_CustomParam_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_CustomMsg_ParamValue_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CustomMsg_ParamValue_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		java.lang.String[] descriptorData = { "\n\025ServerCustomMsg.proto\"\252\001\n\tCustomMsg\022\013\n"
				+ "\003cmd\030\001 \002(\005\022&\n\006params\030\002 \003(\0132\026.CustomMsg.C"
				+ "ustomParam\032K\n\013CustomParam\022\020\n\010paramKey\030\001 "
				+ "\002(\t\022*\n\013paramValues\030\002 \002(\0132\025.CustomMsg.Par"
				+ "amValue\032\033\n\nParamValue\022\r\n\005value\030\001 \003(\tB,\n\031"
				+ "com.netty.game.server.msgB\017ServerCustomM" + "sg" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_CustomMsg_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_CustomMsg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_CustomMsg_descriptor, new java.lang.String[] { "Cmd", "Params", });
		internal_static_CustomMsg_CustomParam_descriptor = internal_static_CustomMsg_descriptor.getNestedTypes().get(0);
		internal_static_CustomMsg_CustomParam_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_CustomMsg_CustomParam_descriptor,
				new java.lang.String[] { "ParamKey", "ParamValues", });
		internal_static_CustomMsg_ParamValue_descriptor = internal_static_CustomMsg_descriptor.getNestedTypes().get(1);
		internal_static_CustomMsg_ParamValue_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_CustomMsg_ParamValue_descriptor, new java.lang.String[] { "Value", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
